# Python 3.11 on purpose: bleach 6.x needs >=3.10, and zerobin/cli.py and
# zerobin/routes.py import distutils, which was removed in 3.12.
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    ZEROBIN_HOST=0.0.0.0 \
    ZEROBIN_PORT=3255 \
    ZEROBIN_DATA_DIR=/data/0bin \
    ZEROBIN_CONFIG_DIR=/config/0bin \
    XDG_DATA_HOME=/data \
    XDG_CONFIG_HOME=/config
# ZEROBIN_*_DIR is only read by `runserver`. The other subcommands (infos,
# set-admin-password, ...) resolve <XDG_*_HOME>/0bin through appdirs, so the
# XDG variables are set to make every subcommand agree on the same paths.

WORKDIR /app

# Install dependencies first so source edits do not bust the pip layer.
COPY pyproject.toml setup.cfg setup.py README.rst ./
COPY zerobin/VERSION zerobin/__init__.py zerobin/
RUN pip install -e .

COPY zerobin/ zerobin/

# Editable install is deliberate: a regular `pip install .` ships a broken
# package because setup.cfg's package_data misses views/*.tpl and VERSION
# (MANIFEST.in is generated by dodo.py and gitignored). Running from /app
# keeps the templates and VERSION file where the code expects them.

RUN useradd --system --create-home --uid 999 zerobin \
    && mkdir -p /data /config \
    && chown -R zerobin:zerobin /data /config /app

USER zerobin

VOLUME ["/data", "/config"]
EXPOSE 3255

ENTRYPOINT ["python", "-m", "zerobin"]
CMD ["runserver"]
